### PR TITLE
FEATURE: Menu item icon configuration

### PR DESCRIPTION
**Pull request by Tom-Alexander**
This prevents the menu_icon being overridden by default. Font-Awesome icons can now be added via configuration.

Example usage:

```
private static $menu_icon_class = 'fa fa-check-circle';
```

### CODE REVIEW

**Comment by stevie-mayhew** [comment]
:+1:

**Comment by Rhym** [comment]
Looks good to me, could you please just run a format on the code? e.g the opening bracket on the same line as the function name on https://github.com/Rhym/silverstripe-cms-theme/pull/7/files#diff-1d8f90f23dc1ce6518144b4ff7f8b3edR47

and the spaces above and below the &.fa declaration in the scss file.

Chhhhhhuuuuuuuurrrrrrrrrrr.

**Comment by Rhym** [comment]
Also, thoughts on adding "fa " by default? Just so we don't have to declare it each time.

**Comment by stevie-mayhew** [comment]
If you want to use another font system then you wont use 'fa' ?

**Comment by Rhym** [comment]
Very true. CARRY ON

**Comment by Tom-Alexander** [comment]
How is that @Rhym?

**Pull request merged**
