### PR TITLE
Fix sub menu title from being blank

### PR DESCRIPTION
**Pull request by 3Dgoo**

### CODE REVIEW

**Comment by tractorcow** [comment]
Could this not be in an `<% if $sectionTitle %>$sectiontitle<% else %>$title<% end_if %>` condition?

**Comment by Rhym** [comment]
Happy to take a PR, @tractorcow

**Review by Rhym — APPROVED** [review]

**Comment by 3Dgoo** [comment]
@tractorcow thank you for the suggestion. Yes. I have made this change.

**Comment by tractorcow** [comment]
Awesome thanks :D

**Comment by nathanbrauer** [comment]
Any ETA on this being tagged? 
@muskie9

**Pull request merged**
